### ISSUE TITLE
Mejorar el landing

### ISSUE THREAD

**Issue by rubenjr0** [ConsejoInfUMA/HackersWeekWeb#10]
## Principal
- Logo

## Secundario
- Poner enlaces en la parte baja del hero?
- Enlaces a cada sección?
- Particulas?
- Texto secundario?

**Comment by josanri** [comment]
¿Podría mejorarse el landing haciendo uso del degradado? El fondo actual parece considerablemente plano.

**Comment by rubenjr0** [comment]
Sería una opción, si. Por ahora estoy pensando en seguir un diseño minimalista, pero podemos ir probando esas cosillas.
