### ISSUE TITLE
Crear componente de talleres y conferencias

### ISSUE THREAD

**Issue by rubenjr0** [ConsejoInfUMA/HackersWeekWeb#5]

**Comment by josanri** [comment]
Se necesita alinear la inscripción y textos adecuadamente.

**Comment by josanri** [comment]
Estaría bien hacer las descripciones con una elipsis.

**Comment by rubenjr0** [comment]
> Estaría bien hacer las descripciones con una elipsis.

https://github.com/jgthms/bulma/issues/1188

**Comment by rubenjr0** [comment]
https://paulbakaus.com/tutorials/css/multiline-truncated-text-with-show-more-button-with-just-css/
